# Generated by Django 5.0.7 on 2024-10-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('roomBlock', models.CharField(max_length=15)),
                ('roomCapcity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Lecturer',
            fields=[
                ('slID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('slName', models.CharField(max_length=100)),
                ('slEmail', models.CharField(max_length=50)),
                ('slAge', models.IntegerField()),
                ('slPhone', models.CharField(max_length=12)),
                ('slStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('studentAge', models.IntegerField()),
                ('studentPhone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.room')),
                ('slID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.staff_lecturer')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
    ]
