# Generated by Django 5.0.7 on 2024-10-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
