# Generated by Django 5.0.7 on 2024-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_student_studentemail_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_lecturer',
            name='slPhone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentPhone',
        ),
        migrations.AddField(
            model_name='staff_lecturer',
            name='slPS',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentPS',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
