# Generated by Django 5.0.7 on 2024-10-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_remove_staff_lecturer_slphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
