# Generated by Django 5.0.7 on 2024-10-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_ticket_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('typeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='meetingType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.meetingtype'),
        ),
    ]
