# Generated by Django 5.0.7 on 2024-10-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_meetingtype_ticket_meetingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='meetingType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.meetingtype'),
        ),
    ]
