# Generated by Django 5.0.7 on 2024-10-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_alter_ticket_meetingtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomCapcity',
            new_name='roomCapacity',
        ),
    ]
